version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7.0 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
         PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout  # checkout source code to working directory

      - restore_cache:
          keys:
            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-

      - run:
          name: Install dependencies
          command: |
            pipenv sync --dev

      - save_cache:
          paths:
            - ~/app/.venv
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Linting
          command:
            pipenv run flake8

      - run:
          name: Run tests
          command: |
            pipenv run python runtests.py --coverage
            pipenv run coverage-badge -o coverage.svg

      - store_artifacts:
          path: ~/app/coverage.svg
